# Generated by Django 3.2.5 on 2021-07-22 23:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='created_by',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
