# Generated by Django 3.2.5 on 2021-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_addcomment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
    ]
